FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt # Vai instalar langchain-cloudflare

COPY agent/ ./agent/

EXPOSE 8001

CMD ["uvicorn", "agent.main:app", "--host", "0.0.0.0", "--port", "8001"]